name: "betterthangreat"
description: "Better Than Great home website. Showcasing work samples, blogs and other content relevant to the branding of the company."

url: "http://localhost:4000"

paginate: 10
layout: default

markdown: rdiscount
permalink: /:categories/:title
highlighter: pygments
